sudo: required
services:
  - docker

before_install:
  - docker build -t wmmk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wmmk/react-test npm test

after_success:
  - docker build -t wmmk/multi-client ./client
  - docker build -t wmmk/multi-nginx ./nginx
  - docker build -t wmmk/multi-server ./server
  - docker build -t wmmk/multi-worker ./worker
  # we need to login to the docker cli
  # we will setup encrypted env values
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push it to docker-hub
  - docker push wmmk/multi-client
  - docker push wmmk/multi-nginx
  - docker push wmmk/multi-server
  - docker push wmmk/multi-worker




